# Generated by Django 4.2.6 on 2023-10-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=120)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures')),
                ('aadhar_card_file', models.FileField(null=True, upload_to='aadhar_files')),
                ('pan_card_file', models.FileField(null=True, upload_to='pan_files')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
