# Generated by Django 4.2.6 on 2023-10-11 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.TextField()),
                ('product_price', models.BigIntegerField()),
                ('product_quantity', models.IntegerField()),
                ('product_amount', models.BigIntegerField()),
                ('order_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('pb_discount', models.BigIntegerField()),
                ('pa_discount', models.BigIntegerField()),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
