# Generated by Django 4.2.6 on 2023-10-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_orderdetailsmodel_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='discount_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
